services:
  - type: web
    name: voxel-multiplayer-game
    env: node
    plan: free
    buildCommand: npm --prefix voxel-multiplayer-game install
    startCommand: npm --prefix voxel-multiplayer-game start
    autoDeploy: true
